exclude: '^(logs/)'

repos:
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        args: [--style, '{based_on_style: google, indent_width: 2, column_limit: 80, allow_split_before_dict_value: false}']
        additional_dependencies: [toml]

  - repo: https://github.com/PyCQA/isort
    rev: 8.0.0
    hooks:
      - id: isort
        stages: [pre-commit]
        args: ["--profile", "google", "--line-length", "80", "-p", "fetch_emails", "-p", "parse_html", "-p", "generate_report", "-p", "credentials"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.html$
      - id: end-of-file-fixer
        exclude: \.html$
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=50000'] # Set higher because of HTML files

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, pandas-stubs, types-beautifulsoup4]
        exclude: ^(tests/|old/|creds\.py)
        args: [--ignore-missing-imports, --explicit-package-bases]

  - repo: https://github.com/PyCQA/pylint
    rev: v4.0.5
    hooks:
      - id: pylint
        args:
          - "--disable=C0114,C0115,C0116,R0903,W0718,C0301,C0415,E0401,W0212,W1514,C0321,W1203,W0201,W0611,R0912,R0915,W1309,W0702,W0109,R0914,R1702,R1730,W0613,R1723,W0612,W0511,C0103,C0302,R1731,R0913,W0640,E1101,W0621,W3101,W0105,R0801"
          - "--indent-string=  "
        exclude: |
            (?x)^(
                tests/|
                old/
            )
